### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GamerGMD** [scomans/MyPet#1479]
[17:54:30] [Server thread/INFO]: Gamer6MD issued server command: /pcst
[17:54:30] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'pcst' in plugin MyPet v3.1 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:760) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1944) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1783) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1764) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1101) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3164-Spigot-f773da8-b069f22]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by andris155** [comment]
The MyPet is not work on 1.17.
